version: "2.1"
description: "Simulate 'Only build pull requests' with git-flow"

jobs:
  check_enable_to_build:
    executor: simple_executor
    parameters:
      build_branches:
        description: "branch names to build without pull requests. It is separated by spaces"
        default: "master develop"
        type: string
      api_token:
        description: "Personal API token in CircleCI. require to call cancel api"
        type: string
    steps:
      - my_inline_command:
          build_branches: <<parameters.build_branches>>
          api_token: <<parameters.api_token>>

commands:
  my_inline_command:
    parameters:
      build_branches:
        type: string
      api_token:
        type: string
    steps:
      - run:
          name: Check enable to build
          shell: /bin/bash
          command: |
            for build_branch in <<parameters.build_branches>>; do
              if [ $CIRCLE_BRANCH = $build_branch ]; then
                exit 0
              fi
            done
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              exit 0
            else
              echo "If a pull request has not been created, CI will not be executed"
              curl -X POST https://circleci.com/api/v2/workflow/${CIRCLE_WORKFLOW_ID}/cancel \
              -H 'Accept: application/json' \
              -H 'Circle-Token: <<parameters.api_token>>'
            fi

executors:
  simple_executor:
    parameters:
      version:
        type: string
        default: "2.4"
    docker:
      - image: circleci/ruby:<<parameters.version>>